service: yandeh-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: sa-east-1
  stage: dev
  apiGateway:
    restApiId: test
    restApiRootResourceId: test

functions:
  - ${file(./src/functions/product/find/handler.yml)}

plugins:
  - serverless-plugin-typescript
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3000
    host: '0.0.0.0'

