service: yandeh-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: sa-east-1
  stage: dev

functions:
  websocketConnect:
    handler: src/functions/websocket/connect.handler
    events:
      - websocket:
          route: $connect
  websocketDisconnect:
    handler: src/functions/websocket/disconnect.handler
    events:
      - websocket:
          route: $disconnect
  websocketDefault:
    handler: src/functions/websocket/default.handler
    events:
      - websocket:
          route: $default

plugins:
  - serverless-plugin-typescript
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3000
    host: '0.0.0.0'
    websocketPort: 3001
