websocketDefault:
    handler: src/functions/websocket/default.handler
    timeout: 900
    events:
      - websocket:
          route: $default
    environment:
      IS_OFFLINE: true
      WEBSOCKET_ENDPOINT: yandeh-challenge-api-app-1:3001